In [5]:
import numpy as np

In [6]:
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [7]:
np.sum(arr)

210

In [8]:
np.mean(arr)

10.5

In [9]:
np.median(arr)

10.5

In [10]:
np.std(arr)

5.766281297335398

In [11]:
arr>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [16]:
np.where(arr>10)

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)

In [25]:
arr1 = np.arange(1,17).reshape(4,4)
print (arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [31]:
arr1 [:,1] = arr1 [:,3]

In [32]:
arr1

array([[ 1,  4,  3,  4],
       [ 5,  8,  7,  8],
       [ 9, 12, 11, 12],
       [13, 16, 15, 16]])

In [44]:
arr1[0,:]

array([1, 4, 3, 4])

In [46]:
row_sum = np.sum(arr1, axis=1)

In [47]:
print(row_sum)

[12 28 44 60]


In [49]:
columns_sum = np.sum(arr1, axis=0)

In [50]:
print(columns_sum)

[28 40 36 40]


In [10]:
arr21 = np.random.randint(1,21,size=(3,3))

arr22 = np.random.randint(1,21,size=(3,3))

In [11]:
print(arr21)
print(arr22)

[[19  4  1]
 [11 12  6]
 [11  7 19]]
[[12 19  3]
 [15  2  2]
 [14 12  5]]


In [13]:
add = arr21 + arr22 
print(add)

[[31 23  4]
 [26 14  8]
 [25 19 24]]


In [14]:
subtraction = arr21 - arr22
print(subtraction)

[[  7 -15  -2]
 [ -4  10   4]
 [ -3  -5  14]]


In [15]:
multiplication = arr21 * arr22
print(multiplication)

[[228  76   3]
 [165  24  12]
 [154  84  95]]


In [16]:
dot = np.dot(arr21,arr22)
print(dot)

[[302 381  70]
 [396 305  87]
 [503 451 142]]


In [18]:
arr31 = np.arange(1,13)
arr31

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
arr_reshape = np.reshape(arr31,(3,4))
arr_reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
arr_slice = arr_reshape[1:3,2:4]
arr_slice

array([[ 7,  8],
       [11, 12]])